# Generated by Django 3.0.4 on 2020-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='link',
            field=models.CharField(default='url for project', max_length=100, verbose_name='Work link'),
        ),
    ]
